package fi.notesnap.notesnap.utilities

val languageCodeToNameMap = mapOf(
    "af" to "Afrikaans",
    "sq" to "Albanian",
    "ar" to "Arabic",
    "be" to "Belarusian",
    "bg" to "Bulgarian",
    "bn" to "Bengali",
    "ca" to "Catalan",
    "zh" to "Chinese",
    "hr" to "Croatian",
    "cs" to "Czech",
    "da" to "Danish",
    "nl" to "Dutch",
    "en" to "English (Generic)",
    "eo" to "Esperanto",
    "et" to "Estonian",
    "fi" to "Finnish",
    "fr" to "French",
    "gl" to "Galician",
    "ka" to "Georgian",
    "de" to "German",
    "el" to "Greek",
    "gu" to "Gujarati",
    "ht" to "Haitian Creole",
    "he" to "Hebrew",
    "hi" to "Hindi",
    "hu" to "Hungarian",
    "is" to "Icelandic",
    "id" to "Indonesian",
    "ga" to "Irish",
    "it" to "Italian",
    "ja" to "Japanese",
    "kn" to "Kannada",
    "ko" to "Korean",
    "lt" to "Lithuanian",
    "lv" to "Latvian",
    "mk" to "Macedonian",
    "mr" to "Marathi",
    "ms" to "Malay",
    "mt" to "Maltese",
    "no" to "Norwegian",
    "fa" to "Persian",
    "pl" to "Polish",
    "pt" to "Portuguese",
    "ro" to "Romanian",
    "ru" to "Russian",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "es" to "Spanish",
    "sv" to "Swedish",
    "sw" to "Swahili",
    "tl" to "Tagalog",
    "ta" to "Tamil",
    "te" to "Telugu",
    "th" to "Thai",
    "tr" to "Turkish",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "vi" to "Vietnamese",
    "cy" to "Welsh"
)

fun getLanguageName(languageCode: String): String {
    return languageCodeToNameMap[languageCode] ?: languageCode
}